// Copyright (c) PRO-Robotech
// SPDX-License-Identifier: BUSL-1.1

package main

import (
	"strings"
	"testing"

	annotations "google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
)

// optsWithHTTP собирает MethodOptions с заданным google.api.http-правилом.
func optsWithHTTP(rule *annotations.HttpRule) *descriptorpb.MethodOptions {
	opts := &descriptorpb.MethodOptions{}
	if rule != nil {
		proto.SetExtension(opts, annotations.E_Http, rule)
	}
	return opts
}

func TestPatternBinding_StandardMethods(t *testing.T) {
	cases := []struct {
		name       string
		rule       *annotations.HttpRule
		wantMethod string
		wantPath   string
	}{
		{"get", &annotations.HttpRule{Pattern: &annotations.HttpRule_Get{Get: "/iam/v1/accounts/{account_id}"}}, "GET", "/iam/v1/accounts/{account_id}"},
		{"post", &annotations.HttpRule{Pattern: &annotations.HttpRule_Post{Post: "/iam/v1/accounts"}}, "POST", "/iam/v1/accounts"},
		{"patch", &annotations.HttpRule{Pattern: &annotations.HttpRule_Patch{Patch: "/iam/v1/accounts/{account_id}"}}, "PATCH", "/iam/v1/accounts/{account_id}"},
		{"delete", &annotations.HttpRule{Pattern: &annotations.HttpRule_Delete{Delete: "/iam/v1/accounts/{account_id}"}}, "DELETE", "/iam/v1/accounts/{account_id}"},
		{"put", &annotations.HttpRule{Pattern: &annotations.HttpRule_Put{Put: "/iam/v1/accounts/{account_id}"}}, "PUT", "/iam/v1/accounts/{account_id}"},
		{"custom", &annotations.HttpRule{Pattern: &annotations.HttpRule_Custom{Custom: &annotations.CustomHttpPattern{Kind: "options", Path: "/iam/v1/x"}}}, "OPTIONS", "/iam/v1/x"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			b, ok := patternBinding(c.rule)
			if !ok {
				t.Fatalf("patternBinding(%s): ok=false", c.name)
			}
			if b.method != c.wantMethod || b.path != c.wantPath {
				t.Errorf("patternBinding(%s) = (%s, %s), want (%s, %s)", c.name, b.method, b.path, c.wantMethod, c.wantPath)
			}
		})
	}
}

func TestPatternBinding_NoPattern(t *testing.T) {
	if _, ok := patternBinding(&annotations.HttpRule{}); ok {
		t.Error("patternBinding(empty rule): want ok=false")
	}
}

func TestHTTPBindings_PrimaryPlusAdditional(t *testing.T) {
	rule := &annotations.HttpRule{
		Pattern: &annotations.HttpRule_Post{Post: "/iam/v1/users:invite"},
		AdditionalBindings: []*annotations.HttpRule{
			{Pattern: &annotations.HttpRule_Get{Get: "/iam/v1/users/{user_id}"}},
		},
	}
	got := httpBindings(optsWithHTTP(rule))
	if len(got) != 2 {
		t.Fatalf("httpBindings: got %d bindings, want 2 (primary + additional)", len(got))
	}
	if got[0].method != "POST" || got[0].path != "/iam/v1/users:invite" {
		t.Errorf("primary binding = %+v", got[0])
	}
	if got[1].method != "GET" || got[1].path != "/iam/v1/users/{user_id}" {
		t.Errorf("additional binding = %+v", got[1])
	}
}

func TestHTTPBindings_NoAnnotation(t *testing.T) {
	if got := httpBindings(&descriptorpb.MethodOptions{}); got != nil {
		t.Errorf("httpBindings(no http option): want nil, got %+v", got)
	}
	if got := httpBindings(nil); got != nil {
		t.Errorf("httpBindings(nil): want nil, got %+v", got)
	}
}

func TestSortRoutes_TemplateThenMethod(t *testing.T) {
	routes := []Route{
		{Method: "POST", Template: "/a", FQN: "P.S/Create"},
		{Method: "GET", Template: "/a/{id}", FQN: "P.S/Get"},
		{Method: "GET", Template: "/a", FQN: "P.S/List"},
		{Method: "DELETE", Template: "/a/{id}", FQN: "P.S/Delete"},
	}
	sortRoutes(routes)
	want := []struct{ method, template string }{
		{"GET", "/a"},         // template "/a", GET before POST
		{"POST", "/a"},        //
		{"DELETE", "/a/{id}"}, // template "/a/{id}", DELETE before GET
		{"GET", "/a/{id}"},    //
	}
	for i, w := range want {
		if routes[i].Method != w.method || routes[i].Template != w.template {
			t.Errorf("routes[%d] = (%s, %s), want (%s, %s)", i, routes[i].Method, routes[i].Template, w.method, w.template)
		}
	}
}

func TestRender_GofmtCleanAndComplete(t *testing.T) {
	src, err := render([]Route{
		{Method: "POST", Template: "/iam/v1/accounts", FQN: "kacho.cloud.iam.v1.AccountService/Create"},
	})
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	s := string(src)
	for _, want := range []string{
		"SPDX-License-Identifier: BUSL-1.1",
		"Code generated by the route-table extractor. DO NOT EDIT.",
		"package middleware",
		"var generatedRestRoutes = []restRoute{",
		`{Method: "POST", Template: "/iam/v1/accounts", FQN: "kacho.cloud.iam.v1.AccountService/Create"},`,
	} {
		if !strings.Contains(s, want) {
			t.Errorf("rendered output missing %q", want)
		}
	}
}
